openapi: 3.1.0

info:
  title: Sample API
  version: 0.0.0

paths:
  /api/v1/hello:
    get:
      summary: just say "hello"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                example: hello
